### ISSUE TITLE
problem finding tmp file when invoking separate kotlinc on macOS

### ISSUE THREAD

**Issue by pabl0rg** [cbeust/kobalt#314]
```
Parsed plugin XML file, found: kobalt
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  0.914

Saved /var/folders/gk/ml0b8m817tg8wg0my3819tnc0000gn/T/kobalt2634560458649478965.kt
Script jar file: /Users/juanliska/Documents/work/code/backend-1.7/.kobalt/build/preBuildScript.jar
  Invoking separate kotlinc:
  /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -classpath, /Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar:/Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar, org.jetbrains.kotlin.cli.jvm.K2JVMCompiler, -classpath, /Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-runtime/1.0.6/kotlin-runtime-1.0.6.jar:/Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-stdlib/1.0.6/kotlin-stdlib-1.0.6.jar:/Users/juanliska/.kobalt/wrapper/dist/kobalt-0.914/kobalt/wrapper/kobalt-0.914.jar, -d, /Users/juanliska/Documents/work/code/backend-1.7/.kobalt/build/preBuildScript.jar, , /var/folders/gk/ml0b8m817tg8wg0my3819tnc0000gn/T/kobalt2634560458649478965.kt
Running command in directory /Users/juanliska/Documents/work/code/backend-1.7/.
  /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java -classpath /Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar:/Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.0.6/kotlin-compiler-embeddable-1.0.6.jar org.jetbrains.kotlin.cli.jvm.K2JVMCompiler -classpath /Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-runtime/1.0.6/kotlin-runtime-1.0.6.jar:/Users/juanliska/.kobalt/cache/org/jetbrains/kotlin/kotlin-stdlib/1.0.6/kotlin-stdlib-1.0.6.jar:/Users/juanliska/.kobalt/wrapper/dist/kobalt-0.914/kobalt/wrapper/kobalt-0.914.jar -d /Users/juanliska/Documents/work/code/backend-1.7/.kobalt/build/preBuildScript.jar  /var/folders/gk/ml0b8m817tg8wg0my3819tnc0000gn/T/kobalt2634560458649478965.kt
*****
***** ERROR error: source file or directory not found:
*****
java.lang.IllegalStateException: error: source file or directory not found:
	at com.beust.kobalt.misc.NewRunCommand$Companion$DEFAULT_ERROR$1.invoke(NewRunCommand.kt:53)
	at com.beust.kobalt.misc.NewRunCommand$Companion$DEFAULT_ERROR$1.invoke(NewRunCommand.kt:46)
	at com.beust.kobalt.misc.NewRunCommand.invoke(NewRunCommand.kt:92)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.invokeCompilerInSeparateProcess(KotlinCompiler.kt:114)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler$compilerAction$1.compile(KotlinCompiler.kt:82)
	at com.beust.kobalt.internal.JvmCompiler.doCompile(JvmCompiler.kt:37)
	at com.beust.kobalt.plugin.kotlin.KotlinCompiler.compile(KotlinCompiler.kt:285)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile(KotlinCompiler.kt:308)
	at com.beust.kobalt.plugin.kotlin.KConfiguration.compile$default(KotlinCompiler.kt:307)
	at com.beust.kobalt.app.ParsedBuildFile.generateJarFile(ParsedBuildFile.kt:155)
	at com.beust.kobalt.app.ParsedBuildFile.initPluginUrls(ParsedBuildFile.kt:122)
	at com.beust.kobalt.app.ParsedBuildFile.<init>(ParsedBuildFile.kt:41)
	at com.beust.kobalt.app.BuildFileCompiler.parseBuildFile(BuildFileCompiler.kt:170)
	at com.beust.kobalt.app.BuildFileCompiler.findProjects(BuildFileCompiler.kt:83)
	at com.beust.kobalt.app.BuildFileCompiler.compileBuildFiles(BuildFileCompiler.kt:69)
	at com.beust.kobalt.app.ProjectFinder.initForBuildFile(ProjectFinder.kt:20)
	at com.beust.kobalt.Main.runWithArgs(Main.kt:180)
	at com.beust.kobalt.Main.run(Main.kt:118)
	at com.beust.kobalt.MainKt.mainNoExit(Main.kt:49)
	at com.beust.kobalt.MainKt.main(Main.kt:27)
```

**Comment by cbeust** [comment]
Fixed in 0.917.

**Comment by pabl0rg** [comment]
I am still having this problem.  I'm trying to compile with Kotlin 1.0.6 using the lastest Kobalt (0.927)

```
> cat ~/.config/kobalt/settings.xml
<kobaltSettings>
    <kobaltCompilerVersion>1.0.6</kobaltCompilerVersion>
</kobaltSettings>
```

Can be reproduced probably compiling any project.  Verified with `git@github:pabl0rg/kobalt-mixed-example.git`

**Comment by cbeust** [comment]
Fixed in 0.929. Note that you'll have to add these two lines to `~/.config/kobalt/settings.xml`:

```
    <kobaltCompilerVersion>1.0.6</kobaltCompilerVersion>
    <kobaltCompilerFlags>-Xskip-metadata-version-check</kobaltCompilerFlags>
```

**Comment by pabl0rg** [comment]
Thanks!  Will 0.929 also default to kotlin 1.1 beta 38?

**Comment by cbeust** [comment]
No, still 22. Do you need 38?

-- 
Cédric

**Comment by pabl0rg** [comment]
Sorry I was having a weird problem on CI servers but not my laptop.  Turns out if using jackson kotlin extensions with kotlin 1.1 you can get random and strange errors unless you declare a depenency on kotlin-reflect-1.1-beta-xx
