### ISSUE TITLE
1.0.40 wipes out entire directory on collect()

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#387]
When `Built.kt` contains:

```
    install {
        libDir = "deploy"
        collect(compileDependencies).map { include(it) }
    }
```
Kobalt wipes out the entire directory, but the `.kobalt` and `kobalt` directories:
```
$ ./kobaltw install
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  1.0.49

  Regular compilation time: 4225 ms
  Regular compilation time: 3302 ms
Parallel build starting
     ╔══════════════════════╗
     ║ Building kobalt-test ║
     ╚══════════════════════╝
───── kobalt-test:compile
───── kobalt-test:assemble
───── kobalt-test:install
  Installing .\.\C:\Users\erik\.kobalt\cache\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar to .
*****
***** ERROR Error: Source '.\.\C:\Users\erik\.kobalt\cache\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar' does not exist
*****

Thread report
╔════════════════════════════════════════╗
║  Time (sec) ║ Thread 14                ║
╠════════════════════════════════════════╣
║  0          ║ kobalt-test              ║
╚════════════════════════════════════════╝
          ╔══════════════════════════════════════════════════════════╗
          ║  Project                       ║ Build status ║ Time     ║
          ╠══════════════════════════════════════════════════════════╣
          ╚══════════════════════════════════════════════════════════╝
PARALLEL BUILD SUCCESSFUL (0 SECONDS), sequential build would have taken 0 seconds

erik@Havok 21:59 /k/kotlin/kobalt-test
$ ls -la
total 12K
drwxr-xr-x 1 erik 197609 0 Apr  4 21:59 .
drwxr-xr-x 1 erik 197609 0 Mar 27 12:24 ..
drwxr-xr-x 1 erik 197609 0 Apr  4 21:59 .kobalt
drwxr-xr-x 1 erik 197609 0 Mar 20 16:55 kobalt
```
Test project at https://github.com/ethauvin/kobalt-test

**Comment by cbeust** [comment]
Fixed in 1.0.51, use:

```
    install {
        collect(compileDependencies).forEach {
            copy(it.absolutePath, to("deploy"))
        }
    }
```

**Comment by ethauvin** [comment]
Still not working right:
```
    install {
        libDir = "deploy"
        collect(compileDependencies).forEach {
            copy(it.absolutePath, to("${libDir}/lib"))
        }
    }
```

```
$ ./kobaltw install                                                                                                               
              __ __           __              __   __                                                                             
             / //_/  ____    / /_   ____ _   / /  / /_                                                                            
            / ,<    / __ \  / __ \ / __ `/  / /  / __/                                                                            
           / /| |  / /_/ / / /_/ // /_/ /  / /  / /_                                                                              
          /_/ |_|  \____/ /_.___/ \__,_/  /_/   \__/  1.0.51                                                                      
                                                                                                                                  
  Regular compilation time: 4060 ms                                                                                               
Parallel build starting                                                                                                           
     ╔══════════════════════╗                                                                                                     
     ║ Building kobalt-test ║                                                                                                     
     ╚══════════════════════╝                                                                                                     
───── kobalt-test:compile                                                                                                         
───── kobalt-test:assemble                                                                                                        
───── kobalt-test:install                                                                                                         
  Installing C:\Users\erik\.kobalt\cache\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar to deploy\lib
  Installing C:\Users\erik\.kobalt\cache\commons-lang\commons-lang\2.4\commons-lang-2.4.jar to deploy\lib                         
  Installing K:\java\semver\deploy\semver-0.9.7.jar to deploy\lib                                                                 
  Installing C:\Users\erik\.kobalt\cache\org\apache\velocity\velocity\1.7\velocity-1.7.jar to deploy\lib                          
                                                                                                                                  
Thread report                                                                                                                     
╔════════════════════════════════════════╗                                                                                        
║  Time (sec) ║ Thread 14                ║                                                                                        
╠════════════════════════════════════════╣                                                                                        
║  0          ║ kobalt-test              ║                                                                                        
║  0          ║ kobalt-test (0)          ║                                                                                        
╚════════════════════════════════════════╝                                                                                        
          ╔══════════════════════════════════════════════════════════╗                                                            
          ║  Project                       ║ Build status ║ Time     ║                                                            
          ╠══════════════════════════════════════════════════════════╣                                                            
          ║  kobalt-test                   ║ SUCCESS      ║ 0.26     ║                                                            
          ╚══════════════════════════════════════════════════════════╝                                                            
PARALLEL BUILD SUCCESSFUL (0 SECONDS), sequential build would have taken 0 seconds                                                
                                                                                                                                  
erik@Havok 18:42 /k/kotlin/kobalt-test                                                                                            
$ ls -R deploy                                                                                                                    
deploy:                                                                                                                           
lib                                                                                                                               
                                                                                                                                  
deploy/lib:                                                                                                                       
velocity-1.7.jar                                                                                                                  
```
* The main jar doesn't get installed in the `libDir` as it did before. 
* Not all the files that it says are copied, actually are.
  * Although that might be right behavior because only `velocity` is an actual compile dependency.

```
    dependencies {
       apt(processorJar)
       compile("org.apache.velocity:velocity:1.7", processorJar)
    }
```

**Comment by ethauvin** [comment]
The artifact jar is still not copied to the `target` directory like it was before.

**Comment by cbeust** [comment]
Yes I made this behavior exclusive with having `copy/include` statements.

Either you use `instal{}` (possibly specifying a `target`) or you use a bunch of `copy/include`.

Do you think they shouldn't be mutually exclusive?

**Comment by ethauvin** [comment]
Assuming that down the line, both `include()` and maybe `exclude()` will replace `copy()`, yes.
