### ISSUE TITLE
Kobalt 1.0.64 won't compile after cleaning cache

### ISSUE THREAD

**Issue by ethauvin** [cbeust/kobalt#416]
I removed the `~/.kobalt` by mistake, and now this is what I'm getting trying to compile kobalt:

```
$ ./kobaltw assemble
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  1.0.64

  Regular compilation time: 5169 ms
Parallel build starting
     ╔════════════════════════════╗
     ║ Building kobalt-plugin-api ║
     ╚════════════════════════════╝
───── kobalt-plugin-api:compile
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[DefaultMetadataResolver-0-1] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[DefaultMetadataResolver-0-1] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to create parent directories for tracking file C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to create parent directories for tracking file C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to create parent directories for tracking file C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to canonicalize path C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties: The filename, directory name, or volume label syntax is incorrect
[K-DynamicGraphExecutor-15] WARN org.eclipse.aether.internal.impl.DefaultUpdateCheckManager - Failed to create parent directories for tracking file C:\Users\erik\.kobalt\cache\org\testng\testng\6.11.1-SNAPSHOT\maven-metadata-http:\dl.bintray.com\cbeust\resolver-status.properties
*****
***** ERROR Error: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.testng:testng:jar:6.11.1-SNAPSHOT in Maven (http://repo1.maven.org/maven2/)
*****
```

**Comment by ethauvin** [comment]
Getting the same error on `--update` now, but I just noticed `maven-metadata-http:\dl.bintray.com\` in the paths that it complains about.

**Comment by ethauvin** [comment]
Problem started with `1.0.46`

**Comment by cbeust** [comment]
Fixed (confirmed by TeamCity).

**Comment by ethauvin** [comment]
Not fixed, confirmed by TravisCI, see https://travis-ci.org/ethauvin/kobalt-maven-local

**Comment by cbeust** [comment]
Getting a weird error (see below) but I just uploaded `kobalt-plugin-api:1.0.66`, can you try using this version explicitly?

```
~/t/kobalt-maven-local$ k assemble
            _  __          _               _   _
           | |/ /   ___   | |__     __ _  | | | |_
           | ' /   / _ \  | '_ \   / _` | | | | __|
           | . \  | (_) | | |_) | | (_| | | | | |_
           |_|\_\  \___/  |_.__/   \__,_| |_|  \__|  1.0.66

  Regular compilation time: 4487 ms
  >>> Using: kobaltBuild/libs/kobalt-maven-local-0.5.2.jar
  Regular compilation time: 1324 ms
*****
***** ERROR Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: org/apache/maven/settings/building/DefaultSettingsBuilderFactory
  at net.thauvin.erik.kobalt.plugin.maven.local.MavenLocalPlugin.<init>(MavenLocalPlugin.kt:45)
  while locating net.thauvin.erik.kobalt.plugin.maven.local.MavenLocalPlugin
```

**Comment by ethauvin** [comment]
Having the same issue, for some reason kobalt no longer likes:

```
compile("org.apache.maven:maven-settings-builder:3.3.9")
```

I didn't want to get my code in the way, so I created a new project, and added the compile dependency, and a couple import to the source. It fails too. Project enclosed.

[kobalt-maven-settings-test.zip](https://github.com/cbeust/kobalt/files/926159/kobalt-maven-settings-test.zip)

The more interesting part is that if you do a `./kobaltw --projectInfo` on that project, it returns nothing. Must some internal conflict.

**Comment by cbeust** [comment]
`        compile("org.apache.maven:maven-settings-builder:3.3.9")` should be in the `dependencies` block, not `dependenciesTest`.

**Comment by ethauvin** [comment]
I did, but it is in the right block on the `kobalt-maven-local` plugin project, and kobalt is complaining about it. Never did before, and nothing has changed in a while.

**Comment by ethauvin** [comment]
Okay, I've figured it out. It was a problem in the buildScript.
